config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('installbase.urls')),
    path('ics/', include('ics.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ics/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import ics_part,ics_inout

app_name = 'ics'

urlpatterns = [
    path('', part_list.as_view(), name='part_list'),
    path('upload/', part_create, name='part_upload'),
    path('inout/<int:pk>', inout_create, name='part_inout'),
    path('inout_del/<int:pk>,<int:inoutid>', inout_delete, name='part_inout_delete'),
]

installbase/backup/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import installbase


app_name = 'installbase'

urlpatterns = [
    path('', InstallBase_list.as_view(), name='installbase_list'),
    path('detail/<int:pk>', DetailView.as_view(model=installbase, template_name='installbase/detail.html'), name='installbase_detail'),
    path('upload/', InstallBase_create, name='installbase_upload'),
    path('delete/<int:pk>', InstallBase_delete.as_view(), name='installbase_delete'),
    path('update/<int:pk>', InstallBaseUpdateView, name='installbase_update'),
    path('clear/<int:pk>', InstallBaseClearView.as_view(), name='installbase_clear'),
    path('undelete/<int:pk>', InstallBase_undelete.as_view(), name='installbase_undelete'),
    path('export/', InstallBase_export, name='installbase_export'),
    path('download/<int:pk>', InstallBase_download_view, name="installbase_download"),
]

installbase/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import installbase

app_name = 'installbase'

urlpatterns = [
    path('', InstallBase_list.as_view(), name='installbase_list'),
    path('detail/<int:pk>', DetailView.as_view(model=installbase, template_name='installbase/detail.html'), name='installbase_detail'),
    path('upload/', InstallBase_create, name='installbase_upload'),
    path('delete/<int:pk>', InstallBase_delete.as_view(), name='installbase_delete'),
    path('update/<int:pk>', InstallBaseUpdateView, name='installbase_update'),
    path('clear/<int:pk>', InstallBaseClearView.as_view(), name='installbase_clear'),
    path('undelete/<int:pk>', InstallBase_undelete.as_view(), name='installbase_undelete'),
    path('export/', InstallBase_export, name='installbase_export'),
    path('download/<int:pk>', InstallBase_download_view, name="installbase_download"),
    path('rack_detail/<int:pk>', InstallBase_Rack_view, name='rack_detail'),
    path('rack_update/<int:pk>', InstallBase_Rack_update, name='rack_update'),
    path('storage_info/<int:pk>', storage_info, name='storage_info'),
]


installbase/backup/backup/models.py
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField
from uuid import uuid4
from datetime import datetime
import os
from django.conf import settings

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    upload_name = filename
    return '/'.join(['upload_file/', ymd_path, upload_name])



LICENSE = (
    ('CIFS', 'CIFS'),
    ('NFS', 'NFS'),
    ('FCP', 'FCP'),
    ('iSCSI', 'iSCSI'),
    ('FlexClone', 'FlexClone'),
    ('SnapMirror', 'SnapMirror'),
    ('SnapRestore', 'SnapRestore'),
)

class installbase(models.Model):
    licensed = MultiSelectField(choices=LICENSE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    customer = models.CharField(max_length=100)
    production = models.BooleanField(default=True)
    installedat = models.CharField(max_length=100)
    project_name = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    osversion = models.CharField(max_length=100)
    serialnumber = models.TextField(max_length=100)
    hostname = models.TextField(max_length=100)
    ipslist = models.TextField()
    shelfmodel = models.TextField()
    disk = models.TextField()
    diskmodel = models.TextField()
    shelfemptyslot = models.TextField()
    slotinfo = models.TextField()
    installedate = models.DateField(null=True, blank=True)
    warrantydate = models.DateField()
    engineername = models.CharField(max_length=100)
    controllereoa = models.DateField(null=True, blank=True)
    controllereos = models.DateField(null=True, blank=True)
    addlist = models.TextField()
    deleted = models.BooleanField(default=False)
    delete_date = models.DateTimeField(auto_now=True)
    sanswitch = models.CharField(max_length=10)
    sanswitchserial = models.CharField(max_length=100, null=True, blank=True)
    sanswitchmodel = models.CharField(max_length=30, null=True, blank=True)
    sanswitchhostname = models.TextField(null=True, blank=True)
    sanswitchport = models.IntegerField(null=True, blank=True)
    sanswitchportlicense = models.IntegerField(null=True, blank=True)
    sanswitchipaddress = models.TextField(null=True, blank=True)
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(null=True, blank=True, max_length=50)
    customer_manager = models.CharField(null=True, blank=True, max_length=50)


    class Meta:
        ordering = ['-installedate']

    def __str__(self):
        return self.hostname

    def get_absolute_url(self):
        return reverse('installbase:installbase_detail', args=[self.id])

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(installbase, self).delete(*args, **kargs)

installbase/backup/backup/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib import messages
from django.views.generic.edit import DeleteView, UpdateView
from django.shortcuts import redirect
from django.db.models import Q
from django.http import HttpResponse
import csv
from installbase.forms import InstallBaseform
from .models import installbase
import urllib
from urllib.parse import urlparse
import os
from django.http import Http404
import mimetypes
from django.shortcuts import get_object_or_404
from django.conf import settings


class InstallBase_list(ListView):
    model = installbase
    template_name = 'installbase/list.html'
    context_object_name = 'installbase_list'

    def get_queryset(self):
        global search_installbase_list
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        order = self.request.GET.get('order', '')
        installbase_list = installbase.objects.order_by('-id')

        if order:
            if order == 'id':
                installbase_list = installbase.objects.order_by('-id')
            elif order == 'production':
                installbase_list = installbase.objects.order_by('-production')
            elif order == 'customer':
                installbase_list = installbase.objects.order_by('-customer')
            elif order == 'project_name':
                installbase_list = installbase.objects.order_by('-project_name')
            elif order == 'osversion':
                installbase_list = installbase.objects.order_by('-osversion')
            elif order == 'sanswitch':
                installbase_list = installbase.objects.order_by('-sanswitch')
            elif order == 'warrantydate':
                installbase_list = installbase.objects.order_by('-warrantydate')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_installbase_list = installbase_list.filter(
                        Q(customer__icontains=search_keyword) | Q(project_name__icontains=search_keyword) | Q(
                            model__icontains=search_keyword) | Q(osversion__icontains=search_keyword) | Q(
                            serialnumber__icontains=search_keyword) | Q(hostname__icontains=search_keyword) | Q(
                            ipslist__icontains=search_keyword) | Q(diskmodel__icontains=search_keyword) | Q(
                            addlist__icontains=search_keyword) | Q(licensed__icontains=search_keyword))
                elif search_type == 'customer':
                    search_installbase_list = installbase_list.filter(customer__icontains=search_keyword)
                elif search_type == 'project_name':
                    search_installbase_list = installbase_list.filter(project_name__icontains=search_keyword)
                elif search_type == 'model':
                    search_installbase_list = installbase_list.filter(model__icontains=search_keyword)
                elif search_type == 'osversion':
                    search_installbase_list = installbase_list.filter(osversion__icontains=search_keyword)
                elif search_type == 'serialnumber':
                    search_installbase_list = installbase_list.filter(serialnumber__icontains=search_keyword)
                elif search_type == 'hostname':
                    search_installbase_list = installbase_list.filter(hostname__icontains=search_keyword)
                elif search_type == 'ipslist':
                    search_installbase_list = installbase_list.filter(ipslist__icontains=search_keyword)
                elif search_type == 'diskmodel':
                    search_installbase_list = installbase_list.filter(diskmodel__icontains=search_keyword)
                elif search_type == 'addlist':
                    search_installbase_list = installbase_list.filter(addlist__icontains=search_keyword)
                elif search_type == 'licensed':
                    search_installbase_list = installbase_list.filter(licensed__icontains=search_keyword)
                return search_installbase_list
            else:
                messages.error(self.request, "검색어는 2글자 이상 입력해주세요.")
        return installbase_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
            context['type'] = search_type

        return context

def InstallBase_create(request):
	if request.method == 'POST':
		form = InstallBaseform(request.POST, request.FILES)
		if form.is_valid():
			installbase = form.save(commit=False)
			if request.FILES:
				if 'upload_files' in request.FILES.keys():
					installbase.filename = request.FILES['upload_files'].name
				installbase.save()
			else:
				installbase.save()
			return redirect('/')
	else:
		form = InstallBaseform()
	context = {'form': form}
	return render(request, 'installbase/upload.html', context)

def InstallBaseUpdateView(request, pk):
    Installbase = installbase.objects.get(id=pk)
    if request.method == "POST":
        file_change_check = request.POST.get('fileChange', False)
        file_check = request.POST.get('upload_files-clear', False)

        if file_check or file_change_check:
            os.remove(os.path.join(settings.MEDIA_ROOT, Installbase.upload_files.path))

        form = InstallBaseform(request.POST, request.FILES, instance=Installbase)
        if form.is_valid():
            Installbase = form.save(commit=False)
            if request.FILES:
                if 'upload_files' in request.FILES.keys():
                    Installbase.filename = request.FILES['upload_files'].name
            Installbase.save()
            messages.success(request, "수정되었습니다.")
            return redirect('/detail/' + str(pk))
    else:
        Installbase = installbase.objects.get(id=pk)
        form = InstallBaseform(instance=Installbase)
        return render(request, "installbase/update.html", {'form': form})



class InstallBase_delete(UpdateView):
    model = installbase
    fields = ['deleted']
    template_name = 'installbase/delete.html'

    def form_valid(self, form):
        form.instance.deleted = True
        if form.is_valid():
            # 데이터가 올바르다면
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


class InstallBase_undelete(UpdateView):
    model = installbase
    fields = ['deleted']
    template_name = 'installbase/undelete.html'

    def form_valid(self, form):
        form.instance.deleted = False
        if form.is_valid():
            # 데이터가 올바르다면
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


class InstallBaseClearView(DeleteView):
    model = installbase
    success_url = '/'
    template_name = 'installbase/clear.html'


def InstallBase_export(request):
    response = HttpResponse(content_type='text/csv')

    response.write(u'\ufeff'.encode('utf8'))

    writer = csv.writer(response)
    writer.writerow(
        ['고객사', '설치위치', '프로젝트명', '모델', 'OS버전', '시리얼', '클러스터명', 'IP정보',
         'Shelf 모델', 'Disk', 'Disk 모델', 'Shelf 빈슬롯', '컨트롤러 슬롯정보', '증설 이력', 'SAN Switch 여부', 'SAN Switch 모델', 'SAN Switch 시리얼', 'SAN Switch HostName', 'SAN Switch IP',  'SAN Switch 잔여포트', 'SAN Switch Port License',  '초기 설치일',
         '워런티 종료일', '담당 엔지니어', 'EOA', 'EOS'])

    for installbases in installbase.objects.all().values_list('customer', 'installedat', 'project_name', 'model',
                                                              'osversion', 'serialnumber', 'hostname', 'ipslist',
                                                              'shelfmodel', 'disk', 'diskmodel', 'shelfemptyslot',
                                                              'slotinfo', 'addlist', 'sanswitch', 'sanswitchmodel', 'sanswitchserial', 'sanswitchhostname', 'sanswitchipaddress',  'sanswitchport', 'sanswitchportlicense', 'installedate',
                                                              'warrantydate', 'engineername', 'controllereoa', 'controllereos'):
        writer.writerow(installbases)

        response['Content-Disposition'] = 'attachment; filename="installbase.csv"'
    return response


def InstallBase_download_view(request, pk):
    download = get_object_or_404(installbase, pk=pk)
    url = download.upload_files.url[1:]
    file_url = urllib.parse.unquote(url)

    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(download.filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

installbase/backup/templates/installbase/clear.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="alert alert-danger"><h1>
            {{ object }} 데이터를 완전 삭제하시겠습니까? DB 에서 데이터가 삭제 됩니다.
            </h1>
        </div>
        <form action="" method="post">
            <div style="display:none;">
            {{ form.as_p }}
            {% csrf_token %}
            </div>
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}

installbase/backup/templates/installbase/delete.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <br><br><br><br><br><br><br><br><br><br>
        <div class="alert alert-danger" role="alert">

            <h1> {{ object }} 를 삭제 처리 하시겠습니까?</h1>
        </div>
    <form action="" method="post">
            <div style="display:none;">
            {{ form.as_p }}
            {% csrf_token %}
            </div>
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}

installbase/backup/templates/installbase/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.hostname|truncatechars:10}}
{% endblock %}

{% block content %}
    {% if object.deleted %}
        <s style="color:red">
    {% endif %}
        <br><br><br><br>
        <div class="row">
            <div class="col-2 text-center">고객사 : </div>
            <div class="col text-left">{{ object.customer|linebreaksbr}}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">설치 위치 : </div>
            <div class="col text-left">{{ object.installedat|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">프로젝트명 : </div>
            <div class="col text-left">{{ object.project_name }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">스토리지 모델 : </div>
            <div class="col text-left">{{ object.model }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">OS Version : </div>
            <div class="col text-left">{{ object.osversion }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">Serial Number : </div>
            <div class="col text-left">{{ object.serialnumber|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">Host Name : </div>
            <div class="col text-left">{{ object.hostname|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">License : </div>
            <div class="col text-left">{{ object.licensed|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">IP Lists : </div>
            <div class="col text-left">{{ object.ipslist|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">Shelf Models : </div>
            <div class="col text-left">{{ object.shelfmodel|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">디스크 수량 : </div>
            <div class="col text-left">{{ object.disk|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">디스크 모델 : </div>
            <div class="col text-left">{{ object.diskmodel|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">디스크 빈 슬롯 정보 : </div>
            <div class="col text-left">{{ object.shelfemptyslot|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">컨트롤러 슬롯 정보 : </div>
            <div class="col text-left">{{ object.slotinfo|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">초기 설치일 : </div>
            <div class="col text-left">{{ object.installedate }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">워런티 종료일 : </div>
            <div class="col text-left">{{ object.warrantydate }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">담당 엔지니어 : </div>
            <div class="col text-left">{{ object.engineername }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">고객 담당자 : </div>
            <div class="col text-left">{{ object.customer_manager }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">Controller EOA : </div>
            <div class="col text-left">{{ object.controllereoa }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">Controller EOS : </div>
            <div class="col text-left">{{ object.controllereos }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">SAN Switch : </div>
            <div class="col text-left">
            {% if object.sanswitch == "1" %}
                있음
            {% else %}
                없음
            {% endif %}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        {% if object.sanswitch == "1" %}
            <div class="row">
                <div class="col-2 text-center">SAN Switch Serial : </div>
                <div class="col text-left"> {{ object.sanswitchserial }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
            <div class="row">
                <div class="col-2 text-center">SAN Switch Model : </div>
                <div class="col text-left">{{ object.sanswitchmodel }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
            <div class="row">
                <div class="col-2 text-center">SAN Switch HostName : </div>
                <div class="col text-left">{{ object.sanswitchhostname   }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
            <div class="row">
                <div class="col-2 text-center">SAN Swtich 잔여 포트 : </div>
                <div class="col text-left">{{ object.sanswitchport }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
            <div class="row">
                <div class="col-2 text-center">SAN Swtich 포트라이센스 수량 : </div>
                <div class="col text-left">{{ object.sanswitchportlicense }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
            <div class="row">
                <div class="col-2 text-center">SAN Swtich IP Address : </div>
                <div class="col text-left">{{ object.sanswitchipaddress }}</div>
            </div>
            <div class="row">
                <br>
                <hr>
            </div>
        {% else %}
        {% endif %}
        <div class="row">
            <div class="col-2 text-center">증설 이력 : </div>
            <div class="col text-left">{{ object.addlist|linebreaksbr }}</div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
        <div class="row">
            <div class="col-2 text-center">첨부 파일 : </div>
            <div class="col text-left">
                {% if object.filename %}
                    <a href="{% url 'installbase:installbase_download' installbase.id %}" >{{ object.filename }}</a>
                {%  else %}
                    첨부파일 없음
                {% endif %}
            </div>
        </div>
        <div class="row">
            <br>
            <hr>
        </div>
	{% if object.deleted %}
        </s>
        {% endif %}
        <div class="row">
            {% if object.deleted %}
            {% else %}
            <div class="col-2 text-center">
                <a href="{% url 'installbase:installbase_delete' pk=object.id %}" class="btn btn-warning btn-sm float-center">삭 제</a>
                <a href="{% url 'installbase:installbase_update' pk=object.id %}" class="btn btn-success btn-sm float-center">수 정</a>
            </div>
            {%  endif %}
            {% if object.deleted %}
            <div class="col-9 text-right">
                <a href="{% url 'installbase:installbase_undelete' pk=object.id %}" class="btn btn-warning btn-sm float-left">삭제 취소</a>
                <a href="{% url 'installbase:installbase_clear' pk=object.id %}" class="btn btn-danger btn-sm float-right">완전 삭제</a>
            </div>
            {% else %}
            {% endif %}
                <br>
        </div>
{% endblock %}

installbase/backup/templates/installbase/export.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

installbase/backup/templates/installbase/update.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% block content %}

    <script src="http://code.jquery.com/jquery-3.1.1.js"></script>
    <script>
    $(function(){
        $(document).ready(function () {
            var value = $(this).find("option:selected").val();
            if ( value == 0 ) {
              $("#id_sanswitchserial").val('');
                $("#id_sanswitchserial").attr("disabled", true);
                $("#id_sanswitchmodel").val('');
                $("#id_sanswitchmodel").attr("disabled", true);
                $("#id_sanswitchhostname").val('');
                $("#id_sanswitchhostname").attr("disabled", true);
                $("#id_sanswitchport").val('');
                $("#id_sanswitchport").attr("disabled", true);
                $("#id_sanswitchportlicense").val('');
                $("#id_sanswitchportlicense").attr("disabled", true);
                $("#id_sanswitchipaddress").val('');
                $("#id_sanswitchipaddress").attr("disabled", true);
            }
        })
    })

    $(function(){
        $(document).on("change", "select[name=sanswitch]", function(){
            let value = $(this).find("option:selected").val();
            var flag = true;
            if (value == true) {
                flag = false;
            }
            $("#id_sanswitchserial").val('');
            $("#id_sanswitchserial").attr("disabled", flag);
            $("#id_sanswitchmodel").val('');
            $("#id_sanswitchmodel").attr("disabled", flag);
            $("#id_sanswitchhostname").val('');
            $("#id_sanswitchhostname").attr("disabled", flag);
            $("#id_sanswitchport").val('');
            $("#id_sanswitchport").attr("disabled", flag);
            $("#id_sanswitchportlicense").val('');
            $("#id_sanswitchportlicense").attr("disabled", flag);
            $("#id_sanswitchipaddress").val('');
            $("#id_sanswitchipaddress").attr("disabled", flag);
        });
    })

    $(document).ready(function(){
    $("#upload_files-clear_id").change(function(){
        if($("#upload_files-clear_id").is(":checked")){
            $("#id_filename").val("");
        }else{
            $("#id_filename").val("{{ object.filename }}");
        }
    });

    $("#id_upload_files").change(function(){
        if($("#id_upload_files").val()){
            var file_name=($('input[type=file]')[0].files[0].name);
            $("#id_filename").val(file_name);
        }else{
            $("#id_filename").val("{{ object.filename }}");
        }
    });
});
    </script>

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <br><br><br><br><br>
            <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
    </div>

{% endblock %}

installbase/backup/templates/installbase/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% block content %}

<script src="http://code.jquery.com/jquery-3.1.1.js"></script>
    <script>
    $(function(){
        $(document).ready(function () {
            var value = $(this).find("option:selected").val();
            if ( value == 0 ) {
                $("#id_sanswitchserial").val('');
                $("#id_sanswitchserial").attr("disabled", true);
                $("#id_sanswitchmodel").val('');
                $("#id_sanswitchmodel").attr("disabled", true);
                $("#id_sanswitchhostname").val('');
                $("#id_sanswitchhostname").attr("disabled", true);
                $("#id_sanswitchport").val('');
                $("#id_sanswitchport").attr("disabled", true);
                $("#id_sanswitchportlicense").val('');
                $("#id_sanswitchportlicense").attr("disabled", true);
                $("#id_sanswitchipaddress").val('');
                $("#id_sanswitchipaddress").attr("disabled", true);
            }
        })
    })

    $(function(){
        $(document).on("change", "select[name=sanswitch]", function () {
            var value = $(this).find("option:selected").val();
            var flag = true;
            if ( value == 1 ) {
              flag = false;
            }
            $("#id_sanswitchserial").val('');
            $("#id_sanswitchserial").attr("disabled", flag);
            $("#id_sanswitchmodel").val('');
            $("#id_sanswitchmodel").attr("disabled", flag);
            $("#id_sanswitchhostname").val('');
            $("#id_sanswitchhostname").attr("disabled", flag);
            $("#id_sanswitchport").val('');
            $("#id_sanswitchport").attr("disabled", flag);
            $("#id_sanswitchportlicense").val('');
            $("#id_sanswitchportlicense").attr("disabled", flag);
            $("#id_sanswitchipaddress").val('');
            $("#id_sanswitchipaddress").attr("disabled", flag);
        })
    })
    </script>

    <br><br><br><br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
    </div>
{% endblock %}