config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('installbase.urls')),
    path('ics/', include('ics.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ics/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import ics_part,ics_inout

app_name = 'ics'

urlpatterns = [
    path('', part_list.as_view(), name='part_list'),
    path('upload/', part_create, name='part_upload'),
    path('inout/<int:pk>', inout_create, name='part_inout'),
    path('inout_del/<int:pk>,<int:inoutid>', inout_delete, name='part_inout_delete'),
]

installbase/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import installbase

app_name = 'installbase'

urlpatterns = [
    path('', InstallBase_list.as_view(), name='installbase_list'),
    path('detail/<int:pk>', DetailView.as_view(model=installbase, template_name='installbase/detail.html'), name='installbase_detail'),
    path('upload/', InstallBase_create, name='installbase_upload'),
    path('delete/<int:pk>', InstallBase_delete.as_view(), name='installbase_delete'),
    path('update/<int:pk>', InstallBaseUpdateView, name='installbase_update'),
    path('clear/<int:pk>', InstallBaseClearView.as_view(), name='installbase_clear'),
    path('undelete/<int:pk>', InstallBase_undelete.as_view(), name='installbase_undelete'),
    path('export/', InstallBase_export, name='installbase_export'),
    path('download/<int:pk>', InstallBase_download_view, name="installbase_download"),
    path('rack_detail/<int:pk>', InstallBase_Rack_view, name='rack_detail'),
    path('rack_update/<int:pk>', InstallBase_Rack_update, name='rack_update'),
    path('storage_info/<int:pk>', storage_info, name='storage_info'),
]


templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 11px;
      }
    </style>
    <title>NetApp Install Base {% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-light bg-light" style="width: 1350px">
            <a class="navbar-brand" href="/"><img src="/static/NetApp_logo.png" style="width:80px" alt="">    NetApp Install Base</a>
            <form class="form-inline">
                <ul class="nav text-left">
                    <a class="btn btn-outline-primary" href="{% url 'ics:part_list' %}" role="button">ICS 재고관리시스템</a>
                    <a class="btn btn-outline-success" href="{% url 'installbase:installbase_upload' %}" role="button">장비등록</a>
                    <a class="btn btn-outline-primary" href="{% url 'installbase:installbase_export' %}" role="button">CSV 내보내기</a>
                </ul>
            </form>
        </nav>
    </header>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 REDHEO. Powered By Django 3</p>
    </footer>
</div>
</body>
</html>

templates/base_ics.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 11px;
      }
    </style>
    <title>NetApp Install Base {% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-light bg-light" style="width: 1300px">
            <a class="navbar-brand" href="/ics"><img src="/static/NetApp_logo.png" style="width:80px" alt="">    Inventory Control System 재고관리 시스템</a>
            <form class="form-inline">
                <ul class="nav text-left">
                    <a class="btn btn-outline-primary" href="{% url 'installbase:installbase_list' %}" role="button">NetApp InstallBase</a>
                    <a class="btn btn-outline-success" href="{% url 'ics:part_upload' %}" role="button">Part 등록</a>
                </ul>
            </form>
        </nav>
    </header>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 REDHEO. Powered By Django 3</p>
    </footer>
</div>
</body>
</html>

templates/rack_base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 11px;
      }
    </style>
    <title>NetApp Install Base {% block title %}{% endblock %}</title>
</head>
<body>
<div>
    <header class="header clearfix">
        <nav class="navbar navbar-light bg-light fixed-top">
            <a class="navbar-brand"><img src="/static/NetApp_logo.png" style="width:80px" alt="">    NetApp Install Base</a>
        </nav>
    </header>

    {% block content %}

    {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 REDHEO. Powered By Django 3</p>
    </footer>
</div>
</body>
</html>