config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('installbase.urls')),
    path('ics/', include('ics.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ics/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import ics_part,ics_inout

app_name = 'ics'

urlpatterns = [
    path('', part_list.as_view(), name='part_list'),
    path('upload/', part_create, name='part_upload'),
    path('inout/<int:pk>', inout_create, name='part_inout'),
    path('inout_del/<int:pk>,<int:inoutid>', inout_delete, name='part_inout_delete'),
]

ics/models.py
from django.db import models
from django.urls import reverse
import os


class ics_part(models.Model):
    part_num = models.TextField()
    part_description = models.TextField()
    ea = models.IntegerField(default=0)

class ics_inout(models.Model):
    inout_id = models.ForeignKey(ics_part, on_delete=models.CASCADE)
    part_num = models.TextField(null=True)
    project_name = models.TextField(null=True)
    inout = models.BooleanField(null=True)
    ea = models.IntegerField(null=True)
    ics_update = models.DateField(null=True, blank=False)
    user = models.TextField(null=True)

    class Meta:
        ordering = ['-part_num']

    def __str__(self):
        return self.part_num

    def get_absolute_url(self):
        return reverse('ics:part_list')

ics/forms.py
from django import forms
from .models import ics_part,ics_inout
from bootstrap_datepicker_plus import DatePickerInput


class ics_part_form(forms.ModelForm):
    class Meta:
        model = ics_part
        fields = ['part_num', 'part_description', 'ea']
        widgets = {
            'part_num': forms.TextInput(attrs={'class': 'form-control'}),
            'part_description': forms.TextInput(attrs={'class': 'form-control'}),
            'ea': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'part_num': 'Part Number',
            'part_description': 'Part Description',
            'ea': '초기 수량',
        }

class ics_inout_form(forms.ModelForm):
    class Meta:
        model = ics_inout
        fields = ['inout_id','part_num', 'inout', 'project_name', 'user', 'ea', 'ics_update']
        widgets = {
            'inout_id': forms.TextInput(attrs={'class': 'form-control', 'style': 'display :none'}),
            'part_num': forms.TextInput(attrs={'class': 'form-control'}),
            'ea': forms.TextInput(attrs={'class': 'form-control'}),
            'ics_update': DatePickerInput(format='%Y/%m/%d'),
            'project_name': forms.TextInput(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'class': 'form-control'}),
            'inout': forms.Select(choices=((0, '반입'), (1, '반출'))),
        }
        labels = {
            'part_num': 'Part Number',
            'inout': '반입/반출',
            'project_name': '프로젝트명',
            'user': '사용자',
            'ea': '수량',
            'ics_update': '반입/반출 일자',
        }

ics/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib import messages
from django.db.models import Q
from .forms import *
from django.shortcuts import redirect
from .models import *

class part_list(ListView):
    model = ics_part
    template_name = 'ics/list.html'
    context_object_name = 'part_list'

    def get_queryset(self):
        global search_part_list
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        order = self.request.GET.get('order', '')
        part_list = ics_part.objects.order_by('-id')
        inout_list = ics_inout.objects.order_by('-ics_update')

        if order:
            if order == 'id':
                part_list = ics_part.objects.order_by('-id')
            elif order == 'part_num':
                part_list = ics_part.objects.order_by('-part_num')
            elif order == 'part_description':
                part_list = ics_part.objects.order_by('-part_description')
            elif order == 'ea':
                part_list = ics_part.objects.order_by('-ea')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_part_list = part_list.filter(
                        Q(part_num__icontains=search_keyword) | Q(part_description__icontains=search_keyword))
                elif search_type == 'part_num':
                    search_part_list = part_list.filter(part_num__icontains=search_keyword)
                elif search_type == 'part_description':
                    search_part_list = part_list.filter(part_description__icontains=search_keyword)
                ics = {
                    'part_list': search_part_list,
                    'inout_list': inout_list,
                }
                return ics
            else:
                messages.error(self.request, "검색어는 2글자 이상 입력해주세요.")

        ics = {
            'part_list': part_list,
            'inout_list': inout_list,
        }
        return ics

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
            context['type'] = search_type


        return context


def part_create(request):
    if request.method == 'POST':
        form = ics_part_form(request.POST)
        if form.is_valid():
            part_list = form.save(commit=False)
            part_list.save()
            return redirect('/ics')
    else:
        form = ics_part_form()
    context = {'form': form}
    return render(request, 'ics/upload.html', context)

def inout_create(request, pk):
    part = ics_part.objects.filter(id=pk)[0]
    part_id = part.id
    part_number = part.part_num
    part_ea = part.ea
    if request.method == 'POST':
        form = ics_inout_form(request.POST)
        if form.is_valid():
            part_list = form.save(commit=False)
            inout = part_list.inout
            if inout == 0:
                part.ea = int(part_ea) + int(part_list.ea)
            else:
                part.ea = int(part_ea) - int(part_list.ea)
            part.save()
            part_list.save()
            return redirect('/ics')
    else:
        form = ics_inout_form()
    context = {
        'form': form,
        'part_id': part_id,
        'part_number': part_number,
    }
    return render(request, 'ics/inout.html', context)

def inout_delete(request, pk, inoutid):
    part = ics_part.objects.filter(id=pk)[0]
    part_ea = part.ea
    inout = ics_inout.objects.filter(id=inoutid)[0]
    if request.method == 'POST':
        part_inout = inout.inout
        if part_inout == 0:
            part.ea = int(part_ea) - int(inout.ea)
        else:
            part.ea = int(part_ea) + int(inout.ea)
        inout.delete()
        part.save()
        return redirect('/ics')
    else:
        form = ics_inout_form()
    return render(request, 'ics/inout_del.html')

ics/templates/ics/inout.html
{% extends 'base_ics.html' %}
{% block title %}- Upload{% endblock %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% block content %}

<script src="http://code.jquery.com/jquery-3.1.1.js"></script>
<script>
    $(document).ready(function() {
        $("#id_part_num").val('{{ part_number }}');
        document.getElementById("id_part_num").disabled = true;
        var el = document.querySelector('label[for=id_inout_id]');
        if (el) {
            el.remove();
        }
    })
    $(document).submit(function() {
        document.getElementById("id_part_num").disabled = false;
    })
    $(document).ready(function() {
        $("#id_inout_id").val('{{ part_id }}');
        document.getElementById("id_part_num").disabled = true;
    })
    $(document).submit(function() {
        document.getElementById("id_inout_id").disabled = false;
    })
</script>

    <br><br><br><br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
    </div>
{% endblock %}

ics/templates/ics/inout_del.html
{% extends 'base_ics.html' %}
{% block title %}- Upload{% endblock %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% block content %}

<script src="http://code.jquery.com/jquery-3.1.1.js"></script>
<script>
    $(document).ready(function() {
        $("#id_part_num").val('{{ part_number }}');
        document.getElementById("id_part_num").disabled = true;
    })
    $(document).submit(function() {
        document.getElementById("id_part_num").disabled = false;
    })
    $(document).ready(function() {
        $("#id_inout_id").val('{{ part_id }}');
        document.getElementById("id_part_num").disabled = true;
    })
    $(document).submit(function() {
        document.getElementById("id_inout_id").disabled = false;
    })
</script>

    <br><br><br><br><br>
    <div class="row">
        <div class="col-md-2"></div>
        {{ part_number }}
        <div class="col-md-8">
            <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
                <div class="alert alert-danger" role="alert">
                    <h1> 반입 / 반출 내역을 삭제 하시겠습니까?</h1>
                </div>
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="delete">
            </form>
        </div>
    </div>
{% endblock %}

ics/templates/ics/list.html
{% extends 'base_ics.html' %}
{% block title %}- List{% endblock %}
{% block content %}
    <script src="http://code.jquery.com/jquery-3.1.1.js"></script>
    <script>
        var inout_open = new Array();
        function inout(inout){
            var inout_id = '#inout_' + inout;
            var inout_id_hr = '#inout_' + inout + '_hr';
            if(inout_open[inout] == 0 || inout_open[inout] == null){
                $(inout_id).show()
                $(inout_id_hr).show()
                inout_open[inout] = 1;
            } else {
                $(inout_id).hide()
                $(inout_id_hr).hide()
                inout_open[inout] = 0;
            }
        }
    </script>
    <table  width="1300" align="center">
    <tr>
        <td colspan="12">
            <form action="" method="GET" name="order">
                <div class="col">
                    <div style="float: right;" class="form-row">
                        <div class="form-row">
                            <div class="col" style="margin-top: 20px;">정렬  : </div>
                            <div class="col" style="margin-top: 10px;">
                                <select style="width: 10em;" class="custom-select custom-select-md" name="order">
                                    <option name="order_list" value="id">번호</option>
                                    <option name="order_list" value="production">Part_Number</option>
                                    <option name="order_list" value="customer">Part_Description</option>
                                    <option name="order_list" value="project_name">수량</option>
                                </select>
                            </div>
                            <div class="col" style="margin-top: 10px;">
                                <select style="width: 10em;" class="custom-select custom-select-md" name="type">
                                    <option name="type_list" value="all">전체</option>
                                    <option name="type_list" value="part_num">Part_Number</option>
                                    <option name="type_list" value="part_description">Part_Description</option>
                                </select>
                            </div>
                            <div class="col" style="margin-top: 10px;">
                                <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                    style="width: 15em;" placeholder="검색어를 입력해주세요.">
                            </div>
                            <div class="col" style="margin-top: 10px;">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="search_btn">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </td>
    </tr>
    <tr>
        <td colspan="5"><hr></td>
    </tr>
    <tr>
        <td align="center" width="100"></td>
        <td align="center" width="200">Part Number</td>
        <td align="center" width="200">수량</td>
        <td align="center" width="700">Part Description</td>
        <td align="center" width="100"></td>

    </tr>
    <tr>
        <td colspan="5"><hr></td>
    </tr>
    {% for post in part_list.part_list %}
    <tr onclick="inout('{{ post.id }}');">
        <td align="center" width="100">{{ post.id }}</td>
        <td align="center" width="200">{{ post.part_num }}</td>
        <td align="center" width="200">{{ post.ea }}</td>
        <td align="center" width="700">{{ post.part_description }}</td>
        <td align="center" width="100"><a href="{% url 'ics:part_inout' pk=post.id %}" class="btn btn-sm btn-success">반입/반출 등록</a></td>
    </tr>
    <tr>
        <td colspan="5"><hr></td>
    </tr>
    <tr style="display :none" id="inout_{{ post.id }}">
        <td colspan="5" align="center">
            <table width="1100">
                <tr>
                    <td colspan="6"><hr></td>
                </tr>
                <tr>
                    <td align="center" width="100">날짜</td>
                    <td align="center" width="100">반입/반출</td>
                    <td align="center" width="100">수량</td>
                    <td align="center" width="100">사용자</td>
                    <td align="center" width="600">프로젝트 명</td>
                    <td align="center" width="100"></td>
                </tr>
                {% for inout in part_list.inout_list %}
                    {% if post.id == inout.inout_id.id %}
                <tr>
                    <td colspan="6"><hr></td>
                </tr>
                <tr>
                    <td align="center">{{ inout.ics_update }}</td>
                    {% if inout.inout == 0 %}
                    <td align="center"><span class="badge badge-primary">반입</span></td>
                    {% else %}
                    <td align="center"><span class="badge badge-danger">반출</span></td>
                    {% endif %}
                    <td align="center">{{ inout.ea }}</td>
                    <td align="center">{{ inout.user }}</td>
                    <td align="center">{{ inout.project_name }}</td>
                    <td align="center"><a href="{% url 'ics:part_inout_delete' pk=post.id inoutid=inout.id %}" class="badge badge-danger">X</a></td>
                </tr>

                    {% endif %}
                {% endfor %}
            <tr>
                    <td colspan="6"><hr></td>
            </tr>
            </table>
        </td>
    </tr>
    <tr style="display :none" id="inout_{{ post.id }}_hr">
        <td colspan="5"><hr></td>
    </tr>
    {% endfor %}

    </table>

    <script type="text/javascript">
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };

    var order_list = getUrlParameter('order');
    var type_list = getUrlParameter('type');
    var order = document.getElementsByName('order_list');
    for (var i = 0; i < 4; i++) {
      if (order[i].value === order_list) {
        order[i].setAttribute('selected', 'selected');
      }
    }
    var type = document.getElementsByName('type_list');
    for (var i = 0; i < 3; i++) {
      if (type[i].value === type_list) {
        type[i].setAttribute('selected', 'selected');
      }
    }
    $(function(){
      $(document).on("change", "select[name=order]", function () {
        var value = $(this).find("option:selected").val();
        if ( value == 1 ) {
          flag = false;
        }
        document.order.submit();
      })
    })
    </script>
{% endblock %}

ics/templates/ics/upload.html
{% extends 'base_ics.html' %}
{% block title %}- Upload{% endblock %}

{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

{% block content %}

<script src="http://code.jquery.com/jquery-3.1.1.js"></script>

    <br><br><br><br><br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
    </div>
{% endblock %}